application: enhanced-rarity-850
version: 1
runtime: python27
api_version: 1
threadsafe: yes




handlers:
- url: /stylesheet
  static_dir: stylesheet

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

- url: /post-service
  static_dir: post-servie
- url: /api
  static_dir: api

- url: /assets
  static_dir: assets

- url: /eventsinfo
  static_dir: eventsinfo

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /components
  static_dir: components

- url: /javascript
  static_dir: javascript

- url: /img
  static_dir: img

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
